### ISSUE TITLE
setMaxSpeed(), setAccel() and setDecel TypeError

### ISSUE THREAD

**Issue by andreagavazzi** [Roboteurs/slushengine#7]
When using python 2.7 I get errors on setMaxSpeed(), setAccel() and setDecel.

This is from Terminal

$ spa=Slush.Motor(0)
$ spa.setMaxSpeed(450)

Traceback (most recent call last):
File "", line 1, in
File "/home/pi/slushengine/Slush/Motor.py", line 102, in setMaxSpeed
self.setParam(LReg.MAX_SPEED, self.maxSpdCalc(speed))
File "/home/pi/slushengine/Slush/Motor.py", line 351, in setParam
return self.paramHandler(param, value)
File "/home/pi/slushengine/Slush/Motor.py", line 366, in paramHandler
return self.param(value, param[1])
File "/home/pi/slushengine/Slush/Motor.py", line 327, in param
temp = self.xfer(value >>8)
TypeError: unsupported operand type(s) for >>: 'float' and 'int'

**Comment by andreagavazzi** [comment]
small fix: convert float types in integers before the bitwise operators
temp = self.xfer(**int**(value) ....... )
